version: '3.9'
services:
  bps-service:
    #image: webconbps/service:2023.1.2.44-windowsservercore-ltsc2022
    image: mcr.microsoft.com/windows/servercore:ltsc2022
    container_name: bps-service
    environment:
      - Configuration__BpsDbConfigRaw=Server=host.docker.internal;Database=BPS_Config;User ID=bps;Password=P@ssw0rd
      - Configuration__ExternalWebService__Host=localhost
      - Configuration__ExternalWebService__LicenseServicePort=8002
      - Configuration__ExternalWebService__Port=8003
      - Configuration__BpsSelfHost=true
      - Configuration__Init__DoInit=true
      - Configuration__Init__WebService__LicenseServicePort=8002
      - Configuration__Init__WebService__Port=8003
      - Configuration__Init__ServiceRoles__LicenseService=true
      - Configuration__Init__ServiceRoles__BasicFeatures=true
      - Configuration__Init__ServiceRoles__SolrIndexing=true
    ports:
      - "8002:8002"
      - "8003:8003"
    networks:
      - bps-nat

networks:
  bps-nat:
    external: true